spring:
  datasource:    url: jdbc:mysql://localhost:3306/vehicle
    username: root
    password: slk@SOFT
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:      ddl-auto: update
    show-sql: true
    
#to show rest methods in latest spring boot version
logging:
 level:
  org:
   springframework:
    web:
     servlet:
      mvc:
       method:
        annotation: TRACE
        
server:  port: 9090        
      